# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df9dddf2a74c8335e7d7202388ef93922317726b86093cd0825f3023baf555d4b526860e1bfae62316ffbcae52f66e687049a9cf55e6faa6d5268f4d72676cd

test:
  secret_key_base: 2670f32398685956a3d64974d3d8c370c756afea03432c21256a759cba84992c6da4af3a2acd91decd7c2cb1cc1aa9b5c5b4484cd1ebabb7fb5ab83bc779bdc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
